@BASE_URL={{baseUrl}}/auth

###
POST {{BASE_URL}}/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "test@mail.com",
    "username": "test",
    "password": "test1234"
}

# Login with email
###
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "emailOrUsername": "test@mail.com",
    "password": "test1234"
}

# Login with username
###
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "emailOrUsername": "test",
    "password": "test1234"
}

# Invalid login
###
POST {{BASE_URL}}/login
Content-Type: application/json

{
    "emailOrUsername": "test",
    "password": "test1"
}

###
POST {{BASE_URL}}/refresh

###
POST {{BASE_URL}}/logout

###
GET {{BASE_URL}}/me