@BASE_URL={{baseUrl}}/games

###
GET {{BASE_URL}}

###
POST {{BASE_URL}}
Content-Type: application/json

{
    "slug": "abc-123",
    "whitePlayer": 1,
    "gameMode": "PvC",
    "initialBoardState": "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
}

###
POST {{BASE_URL}}
Content-Type: application/json

{
    "slug": "abc-123",
    "whitePlayer": 1,
    "gameMode": "PvC",
    "initialBoardState": "invalid board state"
}

###
GET {{BASE_URL}}/1

###
PATCH {{BASE_URL}}/1
Content-Type: application/json

{
    "isGameOver": true
}

###
DELETE {{BASE_URL}}/1


# After restrictions to current user only access
###
GET {{BASE_URL}}

###
GET {{BASE_URL}}?slug=RB8W0IyP-lrddmh63
