@BASE_URL={{baseUrl}}/users

###
GET {{BASE_URL}}

###
GET {{BASE_URL}}/1

###
PATCH {{BASE_URL}}/1
Content-Type: application/json

{
    "firstName": "Johnny"
}


###
DELETE {{BASE_URL}}/1

###
GET {{BASE_URL}}/online